version: "3"
services:
  api:
    container_name: sales-api-dev
    image: node:16
    working_dir: /usr/src/sales-api-dev
    restart: always
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./src/:/usr/src/sales-api-dev/src/
      - ./package.json:/usr/src/sales-api-dev/package.json
      - ./tsconfig.json:/usr/src/sales-api-dev/tsconfig.json
    ports:
      - "3000:3000"
