version: "3"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 5432
  api:
    container_name: sales-api
    image: node:16
    working_dir: /usr/src/sales-api
    restart: always
    command: bash -c "npm install --only=prod && npm run compile"
    volumes:
      - ./dist/:/usr/src/sales-api/dist/
      - ./package.json:/usr/src/sales-api/package.json
      - ./tsconfig.json:/usr/src/sales-api/tsconfig.json
      - ./tsconfig.build.json:/usr/src/sales-api/tsconfig.build.json
    ports:
      - "3000:3000"
    links:
      - postgres
